---
- name: Setup Foundry
  hosts: localhost

  tasks:
    - name: Pull Foundry Docker image
      community.docker.docker_image:
        name: "ghcr.io/foundry-rs/foundry:latest"
        source: pull

    - name: Run anvil fork
      community.docker.docker_container:
        name: "foundry_anvil_run"
        image: "ghcr.io/foundry-rs/foundry:latest"
        env:
          ALCHEMY_PRIVATE_API_KEY: "{{ lookup('env','ALCHEMY_PRIVATE_API_KEY') }}"
          ANVIL_BLOCK_TIME: "{{ lookup('env','ANVIL_BLOCK_TIME') }}"
        state: started
        detach: true
        auto_remove: false
        command: >
          /bin/sh -c "anvil --fork-url 'https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_PRIVATE_API_KEY}' --block-time '${ANVIL_BLOCK_TIME}'"
