name: E2E

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  NODE_VERSION: "21.6.2"
  APP_DATABASE_PORT: 8000
  APP_PORT: 3000
  PLAYWRIGHT_TEST_RESULTS_RELATIVE_PATH: test-results/
  PLAYWRIGHT_TEST_RESULTS_ARTIFACT_RETENTION_DAYS: 7
  PLAYWRIGHT_VERSION:

jobs:
  e2e:
    name: End-to-end tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Get Playwright version
        id: playwright-version
        run: |
          PLAYWRIGHT_VERSION=$(npm ls @playwright/test | grep @playwright/test | sed 's/.*@//')
          echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV

      - name: Cache Playwright dependencies
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install Playwright dependencies
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npm run test.e2e.setup

      - name: Install SurrealDB CLI
        run: curl -sSf https://install.surrealdb.com | sh

      - name: Start app database
        uses: JarvusInnovations/background-action@v1
        with:
          run: ./scripts/database-setup.sh
          wait-on: http-get://localhost:${{ env.APP_DATABASE_PORT }}/status

      - name: Provision app database data
        run: ./scripts/database-provision.sh

      - name: Run build
        run: npm run build

      - name: Serve app production build
        uses: JarvusInnovations/background-action@v1
        with:
          run: npm run serve
          wait-on: http-get://localhost:${{ env.APP_PORT }}

      - name: Run tests
        run: npm run test.e2e

      - name: Save results artifact
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: ${{ env.PLAYWRIGHT_TEST_RESULTS_RELATIVE_PATH }}
          retention-days: ${{ env.PLAYWRIGHT_TEST_RESULTS_ARTIFACT_RETENTION_DAYS }}
